# Generated by Django 6.0.6 on 2026-06-22 22:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Complaint Title')),
                ('category', models.CharField(choices=[('ACADEMIC', 'Academic Issues (Grades, Schedule)'), ('FACILITIES', 'Facilities & Infrastructure (Classrooms, Labs)'), ('HOSTEL', 'Hostel & Housing'), ('FINANCE', 'Finance, Scholarships & Fees'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('description', models.TextField(verbose_name='Detailed Description')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_remarks', models.TextField(blank=True, help_text='Notes from the administration handling this case.', null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.CharField(help_text='Format: SCH-YYYY-XXXX', max_length=20, unique=True, verbose_name='School ID / Student ID')),
                ('course_full_name', models.CharField(help_text='e.g., Bachelor of Science in Computer Science', max_length=150, verbose_name='Course Full Name')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
