# Generated by Django 6.0.6 on 2026-06-30 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCMS', '0002_complaint_viewed_alter_complaint_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='admin_remarks',
            field=models.TextField(blank=True, null=True, verbose_name='Admin Remarks'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='category',
            field=models.CharField(choices=[('Academic', 'Academic Issues (Grades, Faculty, Schedule)'), ('Facilities', 'Facilities & Infrastructure (Classrooms, Labs, Restrooms)'), ('Administrative', 'Administrative Services (Registrar, Finance, Billing)'), ('Student Affairs', 'Student Services & Organizations'), ('Others', 'Other General Miscellaneous Inquiries')], default='Others', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='course_full_name',
            field=models.CharField(blank=True, help_text='e.g., Bachelor of Science in Computer Science', max_length=150, null=True, verbose_name='Course Full Name'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='school_id',
            field=models.CharField(blank=True, help_text='Format: SCH-YYYY-XXXX', max_length=20, null=True, unique=True, verbose_name='School ID / Student ID'),
        ),
    ]
