# Generated by Django 6.0.6 on 2026-07-01 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCMS', '0003_alter_complaint_admin_remarks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='course_full_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Course Full Name'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='school_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='School ID / Student ID'),
        ),
    ]
