# Generated by Django 5.2.15 on 2026-07-02 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCMS', '0005_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
