# Generated by Django 5.2.15 on 2026-07-03 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCMS', '0006_notification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='can_submit_complaints',
            field=models.BooleanField(default=True, verbose_name='Submission Privileges Status'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='complaint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='SCMS.complaint'),
        ),
    ]
