# Generated by Django 5.2.15 on 2026-07-03 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCMS', '0007_studentprofile_can_submit_complaints_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurgedAccountLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-deleted_at'],
            },
        ),
    ]
